### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eveTu** [paxcema/KerasGRU4Rec#5]
Hey, 
I saw that there is no license in the repo. 
Can you please explain about using your code? What is permitted?  
Thanks in advance

**Comment by paxcema** [comment]
Hello,

I am not an expert on licenses. 

Having said that, every part of the code that we wrote is MIT licensed. This does not include the data loader, which was done by [yhs-968](https://github.com/yhs968/pyGRU4REC) (and does not seem to have a license), nor the preprocessing file, which is part of the original [implementation](https://github.com/hidasib/GRU4Rec/blob/master/license.txt) and does have a license. If you plan on using their contributions, make sure to check with them for additional guidance.
