### ISSUE TITLE
Set different weights according to a sequence type

### ISSUE THREAD

**Issue by eveTu** [paxcema/KerasGRU4Rec#9]
Thanks for implementing GRU4Rec in Keras. 

I have a more theoretical question,  like in the collaborative filtering approach, we can set the total rank to an item based on different interactions like view, add to cart, purchase. 
It is possible to set different weights to different sequence types in this approach as well? 

Thanks in advance

**Comment by paxcema** [comment]
Hey, thanks for your interest!

If I understand correctly, you want to predict the item ranking based on more than one sequence. I think there are several ways you could do this. Here's a couple of them:

1) A naive approach would be to simply train one recommender per sequence type, then do a weighted average (depending on what sequence you value more) to arrive at the final ranking. We can probably do better, though. 

2) Those sequences could be stacked into a tensor of shape (batch_size, n_sequences, n_items), and use that as input to a single GRU4Rec. For this approach, all sequences should have the same timestamps.

In both cases, I'm assuming the format of every sequence to be like RSC15. If not, you'll have to preprocess them until they do.
